/* insert users */
INSERT INTO seapal.benutzer (benutzername, passwort, vorname, nachname, mail, geburtsdatum, registrierung) VALUES ("dominic", "pwd", "Dominic", "Eschbach", "doeschba@htwg-konstanz.de", DATE("2012-07-04"), DATE("2012-10-03"));
INSERT INTO seapal.benutzer (benutzername, passwort, vorname, nachname, mail, geburtsdatum, registrierung) VALUES ("timo", "pwd", "Timo", "Partl", "tipartl@htwg-konstanz.de", DATE("2012-07-02"), DATE("2012-10-03"));

/* insert boats */
INSERT INTO seapal.bootinfo (bootname, registernummer, segelzeichen, heimathafen, yachtclub, eigner, versicherung, rufzeichen, typ, konstrukteur, laenge, breite, tiefgang, masthoehe, verdraengung, rigart, baujahr, motor, tankgroesse, wassertankgroesse, abwassertankgroesse, grosssegelgroesse, genuagroesse, spigroesse) VALUES ("Titanic", 101, "TI101", "New York", "New York Yacht Club", "George Boat", "Württembergische", "TI", "Schiff", "Peter Schiff", 200, 50, 7, 10, 1000, "T34", 1993, "Duotec 100", 500, 50, 30, 10, 25, 13);
INSERT INTO seapal.bootinfo (bootname, registernummer, segelzeichen, heimathafen, yachtclub, eigner, versicherung, rufzeichen, typ, konstrukteur, laenge, breite, tiefgang, masthoehe, verdraengung, rigart, baujahr, motor, tankgroesse, wassertankgroesse, abwassertankgroesse, grosssegelgroesse, genuagroesse, spigroesse) VALUES ("Queen Mary 2", 80, "QM80", "Dover", "Dover Yacht Club", "Hans Ebert", "Wüstenrot", "QM", "Schiff", "Rainer Berger", 200, 50, 7, 10, 1000, "T20", 1993, "Duotec 100", 500, 50, 30, 10, 25, 13);
INSERT INTO seapal.bootinfo (bootname, registernummer, segelzeichen, heimathafen, yachtclub, eigner, versicherung, rufzeichen, typ, konstrukteur, laenge, breite, tiefgang, masthoehe, verdraengung, rigart, baujahr, motor, tankgroesse, wassertankgroesse, abwassertankgroesse, grosssegelgroesse, genuagroesse, spigroesse) VALUES ("MS Deutschland", 150, "MSD15", "Hamburg", "Hamburg Yacht Club", "Peter Miller", "Allianz", "MSD", "Schiff", "Emil Klaus", 200, 50, 7, 10, 1000, "T27", 1993, "Duotec 100", 500, 50, 30, 10, 25, 13);

/* insert trips */
INSERT INTO seapal.tripinfo (titel, von, nach, skipper, crew, tstart, tende, tdauer, motor, tank) VALUES ("Langer Trip nach England", "Hamburg", "Dover", "Hr. Hein", "Martin Felix Manuel", DATE("2012-07-02"), DATE("2012-07-02"), 300, 1241, true);

/* insert waypoints */
INSERT INTO  `seapal`.`wegpunkte` (`wnr`, `tnr`, `name`, `btm`, `dtm` ,`lat` ,`lng` ,`sog` ,`cog` ,`manoever` ,`vorsegel` ,`wdate` ,`wtime` ,`marker` ,`wcc` ,`icon` ,`temp` ,`airpressure` ,`windspeed` ,`winddirection` ,`precipation` ,`clouds` ,`wavehight` ,`wavedirection`)
VALUES (NULL ,  '1',  'NewYearsEve12NY',  'btm',  'dtm',  '34',  '118',  'sog',  'cog',  'manoever',  'vorsegel',  '2012-12-31',  '23:59:00',  'Ziel', NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL);
INSERT INTO  `seapal`.`wegpunkte` (`wnr`, `tnr`, `name`, `btm`, `dtm` ,`lat` ,`lng` ,`sog` ,`cog` ,`manoever` ,`vorsegel` ,`wdate` ,`wtime` ,`marker` ,`wcc` ,`icon` ,`temp` ,`airpressure` ,`windspeed` ,`winddirection` ,`precipation` ,`clouds` ,`wavehight` ,`wavedirection`)
VALUES (NULL,  '1',  'TodaysWeatherKN',  'btm',  'dtm',  '47',  '9',  'sog',  'cog',  'manoever',  'vorsegel',  '2013-06-20',  '09:45:00',  'Ziel', NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL);
INSERT INTO  `seapal`.`wegpunkte` (`wnr`, `tnr`, `name`, `btm`, `dtm` ,`lat` ,`lng` ,`sog` ,`cog` ,`manoever` ,`vorsegel` ,`wdate` ,`wtime` ,`marker` ,`wcc` ,`icon` ,`temp` ,`airpressure` ,`windspeed` ,`winddirection` ,`precipation` ,`clouds` ,`wavehight` ,`wavedirection`)
VALUES (NULL ,  '1',  'TokioIn10Days',  'btm',  'dtm',  '35',  '139',  'sog',  'cog',  'manoever',  'vorsegel',  '2013-06-30',  '12:30:00',  'Ziel', NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL);
INSERT INTO  `seapal`.`wegpunkte` (`wnr`, `tnr`, `name`, `btm`, `dtm` ,`lat` ,`lng` ,`sog` ,`cog` ,`manoever` ,`vorsegel` ,`wdate` ,`wtime` ,`marker` ,`wcc` ,`icon` ,`temp` ,`airpressure` ,`windspeed` ,`winddirection` ,`precipation` ,`clouds` ,`wavehight` ,`wavedirection`)
VALUES (NULL,  '1',  'CapeTownIn1Month',  'btm',  'dtm',  '35',  '18',  'sog',  'cog',  'manoever',  'vorsegel',  '2013-07-20',  '15:00:00',  'Ziel', NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL , NULL);
